name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools zip unzip openjdk-17-jdk libffi-dev libssl-dev \
              libsqlite3-dev libjpeg-dev zlib1g-dev autoconf automake libtool pkg-config \
              libncurses5 libncurses5-dev libncursesw5 libncursesw5-dev

          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Create buildozer.spec (if not exists)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
