name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Updated to v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Debug APK Path
        run: ls -alh build/app/outputs/flutter-apk/
        if: always() # Run even if build fails

      - name: Verify Flutter Environment
        run: flutter doctor --verbose
        if: failure() # Run only on failure

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error # Fail if APK is missing
          retention-days: 30