name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify project structure
        run: |
          pwd
          ls -alh
          find . -name pubspec.yaml
        # Helps confirm if pubspec.yaml exists and where

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/pubspec.lock
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5' # Update to 3.24.x if compatible
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./app # REPLACE with your Flutter project directory, e.g., ./app or ./flutter_project

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./app # REPLACE with your Flutter project directory

      - name: Debug APK Path
        run: ls -alh build/app/outputs/flutter-apk/
        working-directory: ./app # REPLACE with your Flutter project directory
        if: always() # Run even if build fails

      - name: Verify Flutter Environment
        run: flutter doctor --verbose
        working-directory: ./app # REPLACE with your Flutter project directory
        if: failure() # Run only on failure

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk # Adjust path based on working-directory
          if-no-files-found: error
          retention-days: 30